# roles/mariadb/tasks/install.yml
---
- name: Add official MariaDB repository
  ansible.builtin.template:
    src: etc_yum.repos.d_mariadb.repo.j2
    dest: /etc/yum.repos.d/MariaDB.repo
    mode: 0644
  tags: mariadb

- name: Create daemon group with specified gid
  # possible ambiguous replacement: group : ansible.builtin.group | awx.awx.group | microsoft.ad.group
  ansible.builtin.group:
    name: "{{ mariadb_system_user.name }}"
    gid: "{{ mariadb_system_user.gid }}"
    system: true
    state: present
  tags: mariadb

- name: Create daemon user with specified uid
  # possible ambiguous replacement: user : ansible.builtin.user | awx.awx.user | cisco.dnac.user | inspur.ispim.user | inspur.sm.user | lowlydba.sqlserver.user | microsoft.ad.user | sensu.sensu_go.user | theforeman.foreman.user | vultr.cloud.user
  ansible.builtin.user:
    name: "{{ mariadb_system_user.name }}"
    uid: "{{ mariadb_system_user.uid }}"
    system: true
    group: "{{ mariadb_system_user.name }}"
    comment: "{{ mariadb_system_user.comment }}"
    home: "{{ mariadb_system_user.home }}"
    create_home: false
    shell: "{{ mariadb_system_user.shell }}"
  tags: mariadb

- name: Install packages
  ansible.builtin.package:
    name: "{{ mariadb_packages }}"
    state: present
  tags: mariadb

- name: Install python moduls for ansible Python < 3 Centos 7
  ansible.builtin.package:
    name: "MySQL-python"
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == "7"
    #    - ansible_python.version.major is version('3', '<')
  tags: mariadb

- name: Install python moduls for ansible Python < 3.8
  ansible.builtin.package:
    name: "{{ ansible_python.version.major is version('3', '=') | ternary('pyt\
    hon3-PyMySQL', 'python2-PyMySQL') }}"
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version is version('7', '>')
    - ansible_python.version.minor is version('8', '<')
  tags: mariadb

- name: Install python moduls for ansible Python 3.8+
  ansible.builtin.package:
    name: python38-PyMySQL
    state: present
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version is version('7', '>')
    - ansible_python.version.major is version('3', '=')
    - ansible_python.version.minor is version('8', '>=')
  tags: mariadb
