# roles/mariadb/tasks/ubuntu.yml
---
- name: Set discovered Ansible Python interpreter.
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ ansible_facts.python.executable }}"
  when: ansible_python_interpreter is not defined
  tags: mariadb

- name: GPG-Agent and tools
  ansible.builtin.apt:
    name:
      - gpg-agent
      - add-apt-key
      - software-properties-common
      - dirmngr
      - apt-transport-https
    update_cache: true
    state: present
  tags: mariadb

- name: Add an Apt signing key from URL
  ansible.builtin.apt_key:
    url: "{{ mariadb_pgp_key }}"
    state: present
  tags: mariadb

- name: Set mariadb preference for apt
  ansible.builtin.blockinfile:
    block: |
      Package: *
      Pin: origin downloads.mariadb.com
      Pin-Priority: 1000
    create: true
    path: /etc/apt/preferences.d/mariadb-enterprise.pref
    owner: root
    group: root
    mode: '0644'

- name: Add official MariaDB repository
  ansible.builtin.apt_repository:
    repo: "{{ mariadb_apt_repositories }}"
    state: present
  tags: mariadb

- name: Install Install MariaDB
  ansible.builtin.apt:
    name: "{{ mariadb_packages }}"
    state: present
    update_cache: true
  tags: mariadb

- name: Install MySQL-python
  ansible.builtin.apt:
    name: "{{ ansible_python.version.major is version('3', '=') | ternary('pyt\
    hon3-pymysql', 'python-pymysql') }}"
    state: present
  tags: mariadb
