---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint -v -c molecule/common/yamllint.yml .
  ansible-lint -v .

platforms:
  - name: dbcentos7
    hostname: dbcentos7
    image: "geerlingguy/docker-centos7-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    tty: true
    environment:
      container: docker
#   - name: dbcentos8
#     hostname: dbcentos8
#     image: "geerlingguy/docker-centos8-ansible:latest"
#     command: ${MOLECULE_DOCKER_COMMAND:-""}
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:rw
#     privileged: true
#     tty: true
#     environment:
#       container: docker
  - name: dbubuntu22
    hostname: dbubuntu22
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    tty: true
    environment:
      container: docker
#  - name: dbubuntu20
#    hostname: dbubuntu20
#    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
#    #image: "jrei/systemd-ubuntu:20.04"
#    command: ${MOLECULE_DOCKER_COMMAND:-""}
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    privileged: true
#    tty: true
#    environment:
#      container: docker
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../.cache/roles"
verifier:
  name: ansible
